#version 450

layout(set = 0, binding = 0) readonly buffer DataInput
{
    vec4 Input[];
};

layout(set = 0, binding = 1) buffer DataOutput
{
    vec4 Output[];
};

layout(set = 1, binding = 0, rgba32f) uniform image2D InputTex;
layout(set = 1, binding = 1, rgba32f) uniform image2D OutputTex;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    Output[index] = Input[index + 1];
    imageStore(OutputTex, ivec2(index, 0), imageLoad(InputTex, ivec2(0, index)));
}